services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image: skysheng7/dsci522:0a58b63
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
