services:
  jupyter-notebook:
    image: skysheng7/dsci522:3aff360
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
    entrypoint: /bin/bash
    stdin_open: true  # -i
    tty: true         # -t
